# Numpy Package

In [36]:
# Import numpy package
import numpy as np
import matplotlib.pyplot as plt

# numpy.random

## numpy.random.rand()
numpy.random.rand() returns an array of random values in a given shape.

### Example

In [37]:
np.random.rand(3,2)

array([[0.22455761, 0.23792626],
       [0.63421998, 0.71676057],
       [0.43998318, 0.99458847]])

## numpy.random.random_sample()
numpy.random.random_sample returns float (floting point real numbers) in continuous uniform destribution. The interval of which can be specified.

### Example 

In [38]:
np.random.random_sample()

0.6976595602537938

In [39]:
# return 3 by 3 array
np.random.random_sample((3, 2))

array([[0.35624197, 0.20771611],
       [0.60039911, 0.25726752],
       [0.95804443, 0.15934127]])

## numpy.random.choice()
numpy.random.choice() returns random sample of one dimensional array.

### Example

In [40]:
# np.arange(5) and size of 8
np.random.choice(5, 8)

array([1, 4, 0, 1, 0, 1, 4, 0])

# Distributions

## Beta Distribution



## Dirichlet Distribution

https://towardsdatascience.com/dirichlet-distribution-a82ab942a879

<blockquote>The Dirichlet distribution Dir(α) is a family of continuous multivariate probability distributions parameterized by a vector α of positive reals. It is a multivariate generalisation of the Beta distribution. Dirichlet distributions are commonly used as prior distributions in Bayesian statistics.</blockquote>



In [41]:
np.random.dirichlet((12, 10, 3))

array([0.51494063, 0.36303521, 0.12202416])

In [59]:
np.random.dirichlet((1, 1, 1))


array([0.31686854, 0.09638477, 0.58674668])